# This file was generated by GoReleaser. DO NOT EDIT.
class Prion < Formula
  desc "A vim package manager, designed for use with pathogen"
  homepage "https://github.com/Jefferson-Faseler/prion"
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Jefferson-Faseler/prion/releases/download/v0.1.5/prion_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "3f4f0f6d11fce8f4dd97182065b650dbd3e8dcbe5b9e95028e01cf9c54f5a609"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Jefferson-Faseler/prion/releases/download/v0.1.5/prion_0.1.5_Linux_x86_64.tar.gz"
      sha256 "aeb75d6ca711179ae9516b11d0c176d559a217ad41d1b638e709f44cd131a313"
    end
  end
  
  depends_on "git"

  def install
    bin.install "prion"
  end

  test do
    system "#{bin}/prion -v"
  end
end
