# This file was generated by GoReleaser. DO NOT EDIT.
class Prion < Formula
  desc "A vim package manager, designed foor use with pathogen"
  homepage "https://github.com/Jefferson-Faseler/prion"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Jefferson-Faseler/prion/releases/download/v0.1.3/prion_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "eb3bd0dad23cee684ea8ad242ac89e14b36bcb16dcfd35b999147ec5af222988"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Jefferson-Faseler/prion/releases/download/v0.1.3/prion_0.1.3_Linux_x86_64.tar.gz"
      sha256 "3a24230cac2147da32aa79576bf81b9b932746bd605f669f622739ca635ae64f"
    end
  end
  
  depends_on "git"
  depends_on "vim"

  def install
    bin.install "prion"
  end

  test do
    system "#{bin}/prion -v"
  end
end
