# This file was generated by GoReleaser. DO NOT EDIT.
class Prion < Formula
  desc "A vim package manager, designed for use with pathogen"
  homepage "https://github.com/Jefferson-Faseler/prion"
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Jefferson-Faseler/prion/releases/download/v0.1.5/prion_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "ec333f801bd3680165051f9c1a1431a92cf41868f7e5091aadcb92eaf7507a19"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Jefferson-Faseler/prion/releases/download/v0.1.5/prion_0.1.5_Linux_x86_64.tar.gz"
      sha256 "c392595de2b1eab97605578275f9071f0f8e26eb1edd713246e03fd0aaf4f27d"
    end
  end
  
  depends_on "git"

  def install
    bin.install "prion"
  end

  test do
    system "#{bin}/prion -v"
  end
end
